//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common.Utilities {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Common.Utilities.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hyderabad.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4. Collections and Generics.
        /// </summary>
        public static string CollectionsAndGenerics {
            get {
                return ResourceManager.GetString("CollectionsAndGenerics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1. C# 7 New Features.
        /// </summary>
        public static string CSharpFeature {
            get {
                return ResourceManager.GetString("CSharpFeature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5. Delegates and Events.
        /// </summary>
        public static string DelegatesAndEvents {
            get {
                return ResourceManager.GetString("DelegatesAndEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suresh_Adimulam@epam.com.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6. Exception Handling.
        /// </summary>
        public static string ExceptionHandling {
            get {
                return ResourceManager.GetString("ExceptionHandling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suresh.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My name is {0} {1} {2}.
        /// </summary>
        public static string GetFullName {
            get {
                return ResourceManager.GetString("GetFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My integer value: {0}.
        /// </summary>
        public static string IntegerResult {
            get {
                return ResourceManager.GetString("IntegerResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adimulam.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3. LINQ.
        /// </summary>
        public static string Linq {
            get {
                return ResourceManager.GetString("Linq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2. Memory management.
        /// </summary>
        public static string MemoryManagement {
            get {
                return ResourceManager.GetString("MemoryManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kumar.
        /// </summary>
        public static string MiddleName {
            get {
                return ResourceManager.GetString("MiddleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7. Unit Testing.
        /// </summary>
        public static string UnitTesting {
            get {
                return ResourceManager.GetString("UnitTesting", resourceCulture);
            }
        }
    }
}
